### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by FranklinChen** [iliabylich/rust-bison-skeleton#1]
I randomly found your project. Do you plan to provide documentation on how to use it and what your plans are for it?

**Comment by iliabylich** [comment]
Hello. I didn't write any kind of documentation because I changed the code way too frequently.

I guess now it's time to write some docs. 

Just out of curiosity, are you going to use it? I wrote it mostly for https://github.com/lib-ruby-parser/lib-ruby-parser and I didn't expect anyone to come here

**Comment by FranklinChen** [comment]
I'm currently using LALRPOP https://lalrpop.github.io/lalrpop/ for a large project. I also evaluated other Rust parsing tools such as https://softdevteam.github.io/grmtools/master/book/index.html so I am curious why you chose to use Bison in particular, and what advantages this brings you.

**Comment by iliabylich** [comment]
IIRC I wanted to have 3 features that LALRPOP doesn't have:
1. [mid-rules support](https://github.com/lalrpop/lalrpop/issues/551)
2. [tracing](https://www.gnu.org/software/bison/manual/html_node/Enabling-Traces.html)
3. ability to configure and access the state of the parser (as I remember LALRPOP constructs a separate method for each derivation that takes `($1, $2, $3)` as an arglist, and so there's nothing else you can access there)

In general bison has many cool features that are not supported but LALRPOP like counterexample generation, full customization of stack value/token value/loc value etc.

**Comment by iliabylich** [comment]
Sorry for delay.

I've added some docs in https://github.com/iliabylich/rust-bison-skeleton/commit/32dcf1e8e69d5cf71b62e4fdf72fedcb937cab12, closing.
