### ISSUE TITLE
Can you create a compatible flex `.y` file?

### ISSUE THREAD

**Issue by tu6ge** [iliabylich/rust-bison-skeleton#4]
Hi , I am learning flex and bison , and I is learned rust language. and I like rust become it is safte language. I look at `src/test/calc.y` file many times, it has some rust sentence, so I uncertain it can work with flex. Can you give me some help ?

**Comment by iliabylich** [comment]
There's nothing specific to Rust or Yacc/Bison in `calc.y`, so better read guides/docs about them. I'm not the best candidate to teach you how it works.

I have 0 experience with Flex but from what I know it emits tokens in some predefined format, and so your `Parser::yylex` method can modify them as needed.
